# Generated by Django 6.1.1 on 2026-09-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(choices=[('red', 'Red'), ('rose', 'Rose'), ('orange', 'Orange'), ('amber', 'Amber'), ('emerald', 'Emerald'), ('teal', 'Teal'), ('blue', 'Blue'), ('indigo', 'Indigo'), ('purple', 'Purple'), ('fuchsia', 'Fuchsia')], default='red', max_length=20),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='book-open', max_length=50),
        ),
    ]
