# Generated by Django 6.1.1 on 2026-09-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
